# Generated by Django 3.2.12 on 2023-04-10 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiteratureInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('literature_name', models.CharField(max_length=200, verbose_name='文献标题')),
                ('literature_auth', models.CharField(max_length=200, verbose_name='文献作者')),
                ('literature_date', models.CharField(max_length=200, verbose_name='文献日期')),
                ('literature_perm', models.CharField(max_length=200, verbose_name='文献权限')),
                ('is_permited', models.CharField(max_length=200, verbose_name='是否通过审批')),
                ('doc_path', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200, verbose_name='用户名')),
                ('nick_name', models.CharField(max_length=200, verbose_name='微信名')),
                ('gender', models.CharField(choices=[('0', '女'), ('1', '男')], default=1, max_length=20, verbose_name='性别')),
                ('nation', models.CharField(choices=[('0', '汉族'), ('1', '回族'), ('2', '满族')], default=0, max_length=200, verbose_name='民族')),
                ('policy_role', models.CharField(choices=[('0', '党员'), ('1', '团员'), ('2', '群众')], default=2, max_length=20, verbose_name='政治面貌')),
                ('household', models.CharField(default='非农业', max_length=200, verbose_name='户籍类型')),
                ('is_bd', models.BooleanField(default='True', verbose_name='是否八大群体')),
                ('job_status', models.BooleanField(default='True', verbose_name='就业状态')),
                ('id_card', models.CharField(max_length=200, verbose_name='身份证号')),
                ('phone_number', models.CharField(max_length=200, verbose_name='手机号码')),
                ('mig_worker', models.BooleanField(default='True', verbose_name='是否农民工')),
                ('company_name', models.CharField(max_length=200, verbose_name='单位名称')),
                ('labour_union', models.CharField(max_length=200, verbose_name='所属工会')),
                ('join_union', models.DateField(default=datetime.date.today, verbose_name='入会时间')),
                ('weixin_openid', models.CharField(max_length=200, verbose_name='微信ID')),
                ('pic_head', models.ImageField(blank=True, null=True, upload_to='head_image', verbose_name='头像')),
                ('desc', models.CharField(default='-', max_length=200, verbose_name='备注')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
    ]
