# Generated by Django 3.2.12 on 2023-04-10 12:55

import AppModel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literatureinfo',
            name='is_permited',
            field=models.BooleanField(default='False', verbose_name='是否通过审批'),
        ),
    ]
