# Generated by Django 3.2.12 on 2023-04-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppModel', '0002_auto_20230410_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literatureinfo',
            name='doc_path',
            field=models.FileField(upload_to='uploads/', verbose_name='文献路径'),
        ),
    ]
