# Generated by Django 3.2.12 on 2023-04-10 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppModel', '0003_alter_literatureinfo_doc_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='literatureinfo',
            name='literature_class',
            field=models.CharField(choices=[('0', '工程技术'), ('1', '数学与统计'), ('2', '自然科学类')], default=0, max_length=200, verbose_name='文献分类'),
        ),
        migrations.AlterField(
            model_name='literatureinfo',
            name='literature_date',
            field=models.DateField(default=datetime.date.today, verbose_name='文献日期'),
        ),
    ]
