# Generated by Django 3.2.12 on 2023-04-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppModel', '0004_auto_20230410_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='literatureinfo',
            name='literature_subclass',
            field=models.CharField(choices=[('0', '计算机科学类'), ('1', '建筑工程类'), ('2', '数学类'), ('3', '统计学类'), ('4', '物理学'), ('5', '化学'), ('6', '生物学')], default=0, max_length=200, verbose_name='文献子类'),
        ),
    ]
