# Generated by Django 3.2.12 on 2023-04-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppModel', '0005_literatureinfo_literature_subclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='literatureinfo',
            name='upload_user',
            field=models.CharField(default=1, max_length=200, verbose_name='上传用户'),
            preserve_default=False,
        ),
    ]
